### PR TITLE
Ss mail sendout

### PR DESCRIPTION
**Pull request by Stronkness**
Updated the SS Applications receiver with proper mail sending based on the status of the application

### CODE REVIEW

**Comment by Stronkness** [comment]
Have you tried turning on the backend in this branch? It said some weird messages, don't know if it affects the program or not

**Comment by AlexanderHansson4225** [comment]
What messages are you refering to? I am getting an compiling error unfortunly

**Comment by Stronkness** [comment]
That's what I'm referring to. Have to fix it

**Comment by Stronkness** [comment]
The failures have now been fixed! @AlexanderHansson4225

**Pull request merged**
